name: QA
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  
jobs:
  qa-test:
    uses: ./.github/workflows/qa_checks.yml
    with:
      allow_to_fail: true
    secrets: inherit
